from django.conf.urls.defaults import *

urlpatterns = patterns('',
   (r'^/?$', 'ocradmin.ocr.views.index'),
	(r'^binarize/?$', 'ocradmin.ocr.views.binarize'),
	(r'^components/?$', 'ocradmin.ocr.views.components'),
	(r'^convert/?$', 'ocradmin.ocr.views.convert'),
	(r'^segment/?$', 'ocradmin.ocr.views.segment'),
    (r'^reconvert_lines/(?P<task_pk>\d+)/?$', 'ocradmin.ocr.views.reconvert_lines'),
    (r'^task_config/(?P<task_pk>\d+)/?$', 'ocradmin.ocr.views.task_config'),
    (r'^task_transcript/(?P<task_pk>\d+)/?$', 'ocradmin.ocr.views.task_transcript'),
    (r'^results/(?P<task_id>[^\/]+)/?$', 'ocradmin.ocr.views.results'),
    (r'^results/?$', 'ocradmin.ocr.views.multiple_results'),
    (r'^save/(?P<task_pk>\d+)/?$', 'ocradmin.ocr.views.save_transcript'),
    (r'^submit_viewer_binarization/(?P<task_pk>\d+)/?$',
        'ocradmin.ocr.views.submit_viewer_binarization'),
    (r'^transcript/(?P<task_pk>\d+)/?$', 'ocradmin.ocr.views.transcript'),
    (r'^viewer_binarization_results/(?P<task_id>[^\/]+)/?$',
        'ocradmin.ocr.views.viewer_binarization_results'),
    (r'^update_task/(?P<task_pk>\d+)/?$', 'ocradmin.ocr.views.update_task'),
	(r'^test/?$', 'ocradmin.ocr.views.test'),
	(r'^testparams/?$', 'ocradmin.ocr.views.testparams'),
)
